---
- name: "Creating Config"
  hosts: 127.0.0.1
  connection: local 
  tasks:
    - name: Create a config file called '/etc/testconfig.conf'
      copy:
        content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address, hostvars[inventory_hostname].ansible_facts.fqdn, hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
        dest: /etc/testconfig.conf
      delegate_to: localhost
